const express = require('express');
const router = express.Router();
const fs = require('fs');
const path = require('path');

const UPLOADS_DIR = path.join(__dirname, 'uploads');
const MEALS_FILE = path.join(__dirname, 'mealsData.json');

// Ensure uploads directory exists
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

// Helper to read meals JSON file
function readMealsData() {
  try {
    if (!fs.existsSync(MEALS_FILE)) {
      fs.writeFileSync(MEALS_FILE, JSON.stringify([]), 'utf8');
      return [];
    }
    const content = fs.readFileSync(MEALS_FILE, 'utf8');
    return JSON.parse(content || '[]');
  } catch (err) {
    console.error('[THE CHEF] Error reading mealsData.json:', err);
    return [];
  }
}

// Helper to write meals JSON file
function writeMealsData(meals) {
  try {
    fs.writeFileSync(MEALS_FILE, JSON.stringify(meals, null, 2), 'utf8');
    return true;
  } catch (err) {
    console.error('[THE CHEF] Error writing mealsData.json:', err);
    return false;
  }
}

// AI Content Guardrail check
function isAiGeneratedContent(title, contentText) {
  const text = (title + ' ' + contentText).toLowerCase();
  const aiKeywords = [
    'as an ai', 'language model', 'openai', 'chatgpt', 'generated by ai', 
    'ai recipe', 'ai-generated', 'delve into', 'in conclusion', 'testament to'
  ];
  return aiKeywords.some(keyword => text.includes(keyword));
}

/**
 * POST /api/upload
 * Handles base64 image/video file uploads and stores them in the server's uploads/ folder.
 */
router.post('/upload', (req, res) => {
  try {
    const { fileName, fileData, fileType } = req.body;
    if (!fileData) {
      return res.status(400).json({ success: false, error: 'Missing fileData in request body.' });
    }

    // Match base64 prefix
    const matches = fileData.match(/^data:([A-Za-z-+\/]+);base64,(.+)$/);
    let buffer;
    let mimeType = fileType || 'image/jpeg';
    let ext = 'jpg';

    if (matches && matches.length === 3) {
      mimeType = matches[1];
      buffer = Buffer.from(matches[2], 'base64');
    } else {
      buffer = Buffer.from(fileData, 'base64');
    }

    // Determine extension based on mimeType or fileName
    if (mimeType.includes('png')) ext = 'png';
    else if (mimeType.includes('gif')) ext = 'gif';
    else if (mimeType.includes('webp')) ext = 'webp';
    else if (mimeType.includes('video/mp4') || mimeType.includes('mp4')) ext = 'mp4';
    else if (mimeType.includes('video/webm') || mimeType.includes('webm')) ext = 'webm';
    else if (fileName && fileName.includes('.')) {
      ext = fileName.split('.').pop().toLowerCase();
    }

    const uniqueName = `meal-${Date.now()}-${Math.floor(Math.random() * 10000)}.${ext}`;
    const filePath = path.join(UPLOADS_DIR, uniqueName);

    fs.writeFileSync(filePath, buffer);

    const relativeUrl = `/uploads/${uniqueName}`;
    console.log(`[THE CHEF] Media saved to server uploads: ${relativeUrl}`);

    return res.json({
      success: true,
      url: relativeUrl,
      fileName: uniqueName
    });
  } catch (err) {
    console.error('[THE CHEF] File upload error:', err);
    return res.status(500).json({ success: false, error: 'Failed to process media upload.' });
  }
});

/**
 * GET /api/meals
 * Returns all saved secret recipes.
 */
router.get('/meals', (req, res) => {
  const meals = readMealsData();
  res.json({ success: true, meals });
});

/**
 * GET /api/meals/:id
 * Lookup a single recipe by ID (useful for share links).
 */
router.get('/meals/:id', (req, res) => {
  const meals = readMealsData();
  const meal = meals.find(m => String(m.id) === String(req.params.id));
  if (!meal) {
    return res.status(404).json({ success: false, error: 'Recipe not found.' });
  }
  res.json({ success: true, meal });
});

/**
 * POST /api/meals
 * Creates and persists a new secret recipe.
 */
router.post('/meals', (req, res) => {
  try {
    const { id, name, ingredients, procedure, nutrition, imgUrl, videoUrl } = req.body;

    if (!name || !ingredients || !procedure || !nutrition) {
      return res.status(400).json({ success: false, error: 'Missing required recipe fields.' });
    }

    if (!imgUrl && !videoUrl) {
      return res.status(400).json({ success: false, error: 'Uploading pictures or a video is mandatory.' });
    }

    const fullContent = (Array.isArray(ingredients) ? ingredients.join(' ') : ingredients) + ' ' +
                        (Array.isArray(procedure) ? procedure.join(' ') : procedure);
    
    if (isAiGeneratedContent(name, fullContent)) {
      return res.status(400).json({ 
        success: false, 
        error: 'AI-generated recipe content blocked. Only real, human-made recipes are accepted.' 
      });
    }

    const newMeal = {
      id: id || `secret-${Date.now()}`,
      name: String(name).trim(),
      ingredients: Array.isArray(ingredients) ? ingredients : [ingredients],
      procedure: Array.isArray(procedure) ? procedure : [procedure],
      nutrition: String(nutrition).trim(),
      imgUrl: imgUrl || '',
      videoUrl: videoUrl || '',
      createdAt: new Date().toISOString()
    };

    const meals = readMealsData();
    // Prepend new meal so newest shows first
    meals.unshift(newMeal);
    writeMealsData(meals);

    console.log(`[THE CHEF] Saved new secret recipe: "${newMeal.name}" (${newMeal.id})`);
    return res.json({ success: true, meal: newMeal });
  } catch (err) {
    console.error('[THE CHEF] Error saving secret meal:', err);
    return res.status(500).json({ success: false, error: 'Failed to save recipe.' });
  }
});

/**
 * DELETE /api/meals/:id
 * Removes a recipe by ID.
 */
router.delete('/meals/:id', (req, res) => {
  try {
    const mealId = req.params.id;
    let meals = readMealsData();
    const initialLength = meals.length;
    meals = meals.filter(m => String(m.id) !== String(mealId));

    if (meals.length === initialLength) {
      return res.status(404).json({ success: false, error: 'Recipe ID not found.' });
    }

    writeMealsData(meals);
    console.log(`[THE CHEF] Deleted secret recipe: ${mealId}`);
    return res.json({ success: true, id: mealId });
  } catch (err) {
    console.error('[THE CHEF] Error deleting meal:', err);
    return res.status(500).json({ success: false, error: 'Failed to delete recipe.' });
  }
});

module.exports = router;
